/**
 * Export Service
 *
 * Single Responsibility: Bundle project assets into ZIP archives.
 * Creates complete export packages with variants, drift overlays, and montage.
 */

import AdmZip from "adm-zip";
import { getMontageService } from "./montageService";
import { LOCALE_REGISTRY, type LocaleId } from "../domain/value-objects/locale";

// =============================================================================
// Types & Interfaces (Interface Segregation Principle)
// =============================================================================

export interface ExportAssets {
  /** Base image buffer */
  baseImage: Buffer;
  /** Mask image buffer */
  maskImage: Buffer;
  /** Map of locale -> variant buffer */
  variants: Map<LocaleId, Buffer>;
  /** Map of locale -> heatmap buffer */
  heatmaps: Map<LocaleId, Buffer>;
  /** Pre-generated montage buffer (optional) */
  montageBuffer?: Buffer;
}

export interface ExportResult {
  /** ZIP file buffer */
  zipBuffer: Buffer;
  /** Montage buffer (generated if not provided) */
  montageBuffer: Buffer;
}

export interface IExportService {
  createExportPackage(assets: ExportAssets): Promise<ExportResult>;
}

// =============================================================================
// Export Service Implementation
// =============================================================================

/**
 * Export Service
 *
 * Bundles all project assets into a ZIP archive:
 * - base.png
 * - mask.png
 * - variants/{locale}.png
 * - drift/{locale}_heatmap.png
 * - montage_2x2.png
 */
export class ExportService implements IExportService {
  private readonly montageService = getMontageService();

  /**
   * Create complete export package
   */
  async createExportPackage(assets: ExportAssets): Promise<ExportResult> {
    const { baseImage, maskImage, variants, heatmaps, montageBuffer } = assets;

    // Generate montage if not provided
    const finalMontage =
      montageBuffer ?? (await this.generateMontage(baseImage, variants));

    // Create ZIP archive
    const zip = new AdmZip();

    // Add base and mask
    zip.addFile("base.png", baseImage);
    zip.addFile("mask.png", maskImage);

    // Add variants
    for (const [locale, buffer] of variants) {
      zip.addFile(`variants/${locale}.png`, buffer);
    }

    // Add heatmaps
    for (const [locale, buffer] of heatmaps) {
      zip.addFile(`drift/${locale}_heatmap.png`, buffer);
    }

    // Add montage
    zip.addFile("montage_2x2.png", finalMontage);

    // Add README
    const readmeContent = this.generateReadme(
      Array.from(variants.keys()),
      Array.from(heatmaps.keys())
    );
    zip.addFile("README.txt", Buffer.from(readmeContent, "utf-8"));

    const zipBuffer = zip.toBuffer();

    console.log(
      `[ExportService] Created ZIP (${(zipBuffer.length / 1024).toFixed(1)} KB) with ${variants.size} variants`
    );

    return {
      zipBuffer,
      montageBuffer: finalMontage,
    };
  }

  /**
   * Generate montage from base and variants
   */
  private async generateMontage(
    baseImage: Buffer,
    variants: Map<LocaleId, Buffer>
  ): Promise<Buffer> {
    const locales: LocaleId[] = ["es-MX", "fr-CA", "ar"];

    const images = [
      { buffer: baseImage, label: "Original (English)" },
      ...locales
        .filter((locale) => variants.has(locale))
        .map((locale) => ({
          buffer: variants.get(locale)!,
          label: LOCALE_REGISTRY[locale].name,
        })),
    ];

    // Pad to 4 images if needed
    while (images.length < 4) {
      images.push({ buffer: baseImage, label: "Placeholder" });
    }

    return this.montageService.generateMontage({ images });
  }

  /**
   * Generate README content for the export
   */
  private generateReadme(variantLocales: LocaleId[], heatmapLocales: LocaleId[]): string {
    const localeList = variantLocales
      .map((l) => `  - ${l}: ${LOCALE_REGISTRY[l].name}`)
      .join("\n");

    return `LocaleLens Export
=================

This export was generated by LocaleLens, a marketing image localization tool
using the OpenAI Image Gen API.

Contents
--------
- base.png: Original source image
- mask.png: Editable regions mask
- variants/: Localized image variants
${localeList}
- drift/: Drift analysis heatmaps showing changes outside mask
- montage_2x2.png: Side-by-side comparison grid

Locales Generated
-----------------
${variantLocales.map((l) => {
  const meta = LOCALE_REGISTRY[l];
  return `- ${l} (${meta.name}): ${meta.direction === "rtl" ? "RTL" : "LTR"}`;
}).join("\n")}

Notes
-----
- Drift heatmaps visualize pixel changes outside the masked regions
- Blue/cyan indicates low change, red indicates high change
- Images were generated using gpt-image-1.5 or gpt-image-1

Generated with LocaleLens
https://github.com/your-repo/localelens
`;
  }
}

// =============================================================================
// Factory
// =============================================================================

let serviceInstance: ExportService | null = null;

export function getExportService(): ExportService {
  if (!serviceInstance) {
    serviceInstance = new ExportService();
  }
  return serviceInstance;
}

export function createExportService(): ExportService {
  return new ExportService();
}
